name: Cloud check in action
on:
  push:
    branches:
      - main
      - dev
  watch:
    types: started
  workflow_dispatch:
  schedule:
    - cron: 35 3 * * *
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: init secrets
        uses: SpicyPizza/create-envfile@v2.0
        with:
          file_name: .env
      - name: init
        run: npm install
      - name: run
        id: run
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: npm start
